spring:
  security:
    oauth2:
      client:
        registration:
          naver:
            scope: name,email
            client-id: JtD1_5Dx92RKMArlPiY4
            client-name: Naver
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            client-secret: D3gXf2a2OG
        provider:
          naver:
            user-info-authentication-method: response
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
            token-uri: https://nid.naver.com/oauth2.0/token
  profiles:
    include: private-key
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: 'true'
  datasource:
    hikari:
      idle-timeout: '30000'
      maximum-pool-size: '50'
      auto-commit: 'false'
      connection-timeout: '30000'
      max-lifetime: '55000'
      minimum-idle: '5'
    driver-class-name: org.h2.Driver
    password: ''
    username: root
    url: jdbc:h2:mem:root
  h2:
    console:
      enabled: 'true'
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

token:
  expiration_time: '86400000'
  secret: user_token

logging:
  level:
    org:
      hibernate:
        SQL: debug
