spring:
  profiles:
    include: private-key
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: 'true'
  datasource:
    hikari:
      idle-timeout: '30000'
      maximum-pool-size: '50'
      auto-commit: 'false'
      connection-timeout: '30000'
      max-lifetime: '55000'
      minimum-idle: '5'
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: ''
    username: mineuser
    url: jdbc:mysql://175.45.200.176:3306/mine
  h2:
    console:
      enabled: 'true'
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  security:
    oauth2:
      client:
        registration:
          apple:
            client-id: com.bside.Mine.services
            client-secret:
            authorization-grant-type: authorization_code
            redirect-uri: https://mine.directory/login/oauth_apple
        provider:
          apple:
            issuer-uri: https://appleid.apple.com


token:
  expiration_time: '86400000'
  secret: user_token

logging:
  level:
    org:
      hibernate:
        SQL: info
server:
  error:
    whitelabel:
      enabled: false